"""
Django settings for gdrive_project project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-secure-xn_oykn_2gly4d_tuca_ivpe_p5vijqe_2e_orgi5ytn_k87a9b3c5e7f1a'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('true', '1', 'yes')

raw_hosts = os.environ.get('ALLOWED_HOSTS', '*')
ALLOWED_HOSTS = [h.strip() for h in raw_hosts.split(',') if h.strip()] if raw_hosts != '*' else ['*']

# Zero-Knowledge Media At-Rest Encryption Key
MEDIA_ENCRYPTION_KEY = os.environ.get('MEDIA_ENCRYPTION_KEY', '').strip() or None



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drive',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gdrive_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'drive.context_processors.drive_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'gdrive_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Default: Zero-setup SQLite for rapid local testing (db.sqlite3).
# Production: Automatically switches to PostgreSQL when DATABASE_URL or POSTGRES_DB is provided.

DATABASE_URL = os.environ.get('DATABASE_URL')
POSTGRES_DB = os.environ.get('POSTGRES_DB')

if DATABASE_URL:
    from urllib.parse import urlparse, unquote
    parsed_db = urlparse(DATABASE_URL)
    is_sqlite = parsed_db.scheme == 'sqlite'

    if is_sqlite:
        db_path = parsed_db.path.lstrip('/')
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / db_path if db_path else BASE_DIR / 'db.sqlite3',
            }
        }
    else:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': unquote(parsed_db.path.lstrip('/')),
                'USER': unquote(parsed_db.username or ''),
                'PASSWORD': unquote(parsed_db.password or ''),
                'HOST': parsed_db.hostname or 'localhost',
                'PORT': str(parsed_db.port or 5432),
            }
        }
elif POSTGRES_DB:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': POSTGRES_DB,
            'USER': os.environ.get('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': str(os.environ.get('POSTGRES_PORT', '5432')),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploads)
# ==============================================================================
# Architecture Note: In production web applications (both SQLite & PostgreSQL),
# binary file uploads are intentionally kept separate from relational databases
# to avoid database buffer bloat, preserve connection pool capacity, and enable
# fast CDN/direct file streaming.
#
# Strategy 1 (Default): Local disk or mounted persistent volume (/app/media)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Strategy 2 (Cloud Production): AWS S3 / Cloudflare R2 / MinIO Object Storage
# Activated when USE_S3=True or AWS_STORAGE_BUCKET_NAME is configured in environment.
USE_S3 = os.environ.get('USE_S3', 'False').lower() in ('true', '1', 'yes')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')

if USE_S3 or AWS_STORAGE_BUCKET_NAME:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "access_key": os.environ.get('AWS_ACCESS_KEY_ID'),
                "secret_key": os.environ.get('AWS_SECRET_ACCESS_KEY'),
                "bucket_name": AWS_STORAGE_BUCKET_NAME,
                "region_name": os.environ.get('AWS_S3_REGION_NAME', 'us-east-1'),
                "endpoint_url": os.environ.get('AWS_S3_ENDPOINT_URL'),
                "default_acl": None,
                "file_overwrite": False,
            },
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }


# Authentication
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'drive_root'
LOGOUT_REDIRECT_URL = 'login'

# Frame options for previewing PDFs and documents in iframe
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Mock storage limit (15 GB)
USER_STORAGE_LIMIT_BYTES = 15 * 1024 * 1024 * 1024

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==============================================================================
# Security Hardening (Django Built-in Protections)
# ==============================================================================

# Prevent MIME-type sniffing by browsers
SECURE_CONTENT_TYPE_NOSNIFF = True

# Protect against Clickjacking while allowing same-origin document preview iframes
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Referrer Policy to prevent private URLs or share tokens from leaking
SECURE_REFERRER_POLICY = 'same-origin'

# Session Cookie Security
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 1209600  # 2 weeks

# CSRF Cookie Security
CSRF_COOKIE_HTTPONLY = False  # Allows client-side AJAX to read for X-CSRFToken header
CSRF_COOKIE_SAMESITE = 'Lax'

# Production SSL settings (automatically enabled when DEBUG is False)
if not DEBUG:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


