# Generated by Django 5.2.17 on 2026-09-09 09:44

import django.db.models.deletion
import drive.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_folder', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to=drive.utils.user_directory_path)),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(default='application/octet-stream', max_length=120)),
                ('file_extension', models.CharField(blank=True, max_length=30)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_trashed', models.BooleanField(default=False)),
                ('trashed_at', models.DateTimeField(blank=True, null=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('share_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_items', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='drive.driveitem')),
            ],
            options={
                'ordering': ['-is_folder', 'name'],
                'indexes': [models.Index(fields=['owner', 'parent', 'is_trashed'], name='drive_drive_owner_i_e9f9f3_idx'), models.Index(fields=['owner', 'is_starred', 'is_trashed'], name='drive_drive_owner_i_8cc3fe_idx'), models.Index(fields=['owner', 'is_trashed'], name='drive_drive_owner_i_c94182_idx'), models.Index(fields=['share_token'], name='drive_drive_share_t_b6fed1_idx')],
            },
        ),
    ]
