# Generated by Django 5.2.17 on 2026-09-09 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_plan', models.CharField(choices=[('15GB', '15 GB (Free / Basic)'), ('100GB', '100 GB (Standard)'), ('500GB', '500 GB (Premium Pro)')], default='15GB', help_text='Storage tier allocated to this user.', max_length=20)),
                ('custom_storage_limit_bytes', models.BigIntegerField(blank=True, help_text='Optional custom storage limit in bytes. Overrides plan tier if set.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile & Storage Plan',
                'verbose_name_plural': 'User Profiles & Storage Plans',
            },
        ),
    ]
