# Generated by Django 5.2.17 on 2026-09-10 11:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='driveitem',
            index=models.Index(fields=['owner', 'is_folder'], name='drive_drive_owner_i_e12327_idx'),
        ),
    ]
